### ISSUE TITLE
Reading in mapping files vs. directory of .map files

### ISSUE THREAD

**Issue by csbrasnett** [fgrunewald/fast_forward#18]

**Comment by csbrasnett** [comment]
@fgrunewald I've started addressing this with [this](https://github.com/fgrunewald/fast_forward/commit/b24911012c37a387766342ab512bd7633d2d9b44) commit. It should happily now find a directory of .map vs a single .mapping file, but it's getting stuck on the parsing. With the *.charmm.map files, I'm getting problems reading a line with a !BB in, so not sure how to resolve at the minute.

**Comment by fgrunewald** [comment]
@csbrasnett you need to change the map file parser in fast-forward to skip atoms with annotated with '!' In particular this function https://github.com/fgrunewald/fast_forward/blob/dbae07463e549d92d1010675045ca143960338cc/fast_forward/map_file_parers.py#L122-L140

**Comment by fgrunewald** [comment]
should be solved
