### ISSUE TITLE
Sign problem of angles 

### ISSUE THREAD

**Issue by jan-stevens** [fgrunewald/fast_forward#23]
Since 'np.arccos' is used to calculate the angle distributions, the returned value is always positive. This is the convention used by [Numpy](https://numpy.org/doc/stable/reference/generated/numpy.arccos.html). This, however, causes some sign issues while fitting distributions. 

A possible solution is calculating the determinant of 'a matrix' to get the correct sign, see [here](https://math.stackexchange.com/questions/317874/calculate-the-angle-between-two-vectors).

**Comment by fgrunewald** [comment]
Angles are always positive; gromacs does not calculate any negative degree angles
