### ISSUE TITLE
Angle potential parameters with etropic correction

### ISSUE THREAD

**Issue by jmelcr** [fgrunewald/fast_forward#6]
Currently, the program calculates estimates of the angle bending parameters directly from the distribution of the angle from AA trajectory. 
This is correct for angles in restrained environment, like in sugar rings,
but is **incorrect** for angles of freely moving moieties as e.g. in alkanes.

In alkanes, the free movement of the chain favours entropically perpendicular angles (i.e. around 90º)
and disfavours those around 0º and 180º. 
For straight chains, this has a qualitative effect – the resulting estimates are equilibrium angle, e.g. 140º instead of 180º. 
See e.g. here, angle from `pycgmap`-ped Charmm36 (blue: current status, orange: with the entropy correction)
![Figure_1](https://user-images.githubusercontent.com/12782348/107969812-8fa7d400-6fb0-11eb-8984-ba0034d40a35.png)

The correction is simple – use the Jacobi factor of the transformation to remove this entropy from the distribution.
This can be simply done by assigning weights to the angle values
w(ang) = 1.0/sin(ang)

I think this could be implemented either as an CLI option or as a comment in the input itp file.

**Comment by fgrunewald** [comment]
I'll keep this issue in mind for the new interaction estimator. Currently the package doesn't compute initial estimates anymore.
